version: '3'

networks:
  database:
    internal: true
  api:
    internal: true
  proxy:

services:
  mysql-cashflow-api:
    image: mysql:8.0
    container_name: mysql-cashflow-api
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'cashflow'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    expose:
      - 3306
    networks:
      - database

  app-cashflow-api:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: app-cashflow-api
    container_name: app-cashflow-api
    restart: unless-stopped
    networks:
      - api
      - database
    depends_on:
      - mysql-cashflow-api
    healthcheck:
      test: "curl -sS http://app-cashflow-api:8080/actuator/health"
      interval: 1s
      timeout: 30s
      retries: 60
  
  proxy-cashflow-api:
    image: nginx
    container_name: proxy-cashflow-api
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
    networks:
      - proxy
      - api
    depends_on:
      - app-cashflow-api



